### ISSUE TITLE
Docker with reverse proxy issues

### ISSUE THREAD

**Issue by m0ngr31** [seanboyce/ubiblio#6]
Hey @seanboyce! I tried deploying the docker container behind an nginx proxy tonight. It's having an issue since it's trying to load http URLs for the css and js by default.

![image](https://github.com/user-attachments/assets/82202333-ed2f-4e7b-a6d6-7b5e021a036f)

I'm guessing it's based on how `url_for` works? I'm wondering if it's possible to set a base URL as an environment variable or something so this doesn't happen?

**Comment by seanboyce** [comment]
I'm not 100% sure where this issue is arising. Lets try a few things.

## 1

My first instinct is that it's with how uvicorn is launched within Docker. The default launch script (entrypoint.sh) assumes you are using it over LAN, and with no HTTPS support, e.g. :

>exec uvicorn ubiblio.main:app --host 0.0.0.0 --port 8000

Could you try moving your cert files into the docker container and launching with 

> exec uvicorn ubiblio.main:app --host 0.0.0.0 --port 8000 --ssl-keyfile "/etc/letsencrypt/live/my_domain/privkey.pem" --ssl_certfile "/etc/letsencrypt/live/my_domain/fullchain.pem"

(updating the paths to wherever your cert files are. While you are changing commands, you can also switch to gunicorn using the command in the setup docs for some extra power if you want.)

This would let ubiblio handle all the SSH on its end. In the back of my mind, I've been trying to think of a way to automate this with Docker, but it might be a few weeks before I figure out a good solution.

## 2

The files that are returning warnings look like they are the files that ubiblio serves out of /static, which is set like so in main.py:

> app.mount("/static", StaticFiles(directory="static"), name="static")

There are not any hardcoded URLs in the app or anything, but you can try editing that one line if you want to give it a specific URL. If that works, I can just add an environment var for it.

## 3

On my end, I use apache2 for the reverse proxy. If the above methods don't bear fruit, I can share my config and also run some tests on my end. Oh, also maybe check CORS settings. That one always does me in.

## Notes on upcoming new ubiblio version

Just as an aside, I'm planning to push out a fairly major upgrade over the next week or so. I'm hoping to finish it today (in the dev branch) and test over the week before deploying. If you're planning to do a lot of data entry, it might be worth waiting for the new version if the new features below benefit you.

It adds a lot of database management stuff (export books as CSV, a web interface to backup + download / upload / restore the DB) that will be super useful for the people that run uBiblio via Docker. It also adds a config panel that lets you enable cover images for books and some custom fields.

**Comment by m0ngr31** [comment]
I submitted a new PR to hopefully fix the issue - I think it's caused by Uvicorn not forwarding the proper headers. #8 

I'm excited to see what the new features look like! I did notice that when I add books by ISBN they all get categorized as Sci-Fi, not sure if that's just something on my end or not

**Comment by seanboyce** [comment]
Merged! I'll tentatively close this issue.

I guess every book is Sci-Fi to someone at some point in history :P

Actually I just have the select box in the form for adding a new book defaulting to Sci-Fi by mistake. The ISBN auto-adder doesn't actually get the genre -- only the title, author, and summary. I'll fix it in dev and the default value will be 'Uncategorized' or something in the upcoming version.

**Comment by m0ngr31** [comment]
BTW, this did fix the reverse proxy issues I was facing
